# Generated by Django 2.1.4 on 2019-04-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
